# © 2024 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up node 
      uses: actions/setup-node@v4
      with:
        node-version: lts
    - name: install dependencies
      run: |  
        npx next telemetry disable
        npm install
    - name: build
      run: |       
        npm run build