# © 2024 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: license_check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up node 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.npm_package_engines_node}}
    - name: install dependencies
      run: |       
        npx next telemetry disable
        npm install       
    - name: license check
      run: |
        npm run license-check
